import { useEffect, useState } from "react";
import api from "../api/client";
import { useAuth } from "../context/AuthContext";

const TABS = [
  ["active", "Active Patients"],
  ["discharged", "Discharged"],
  ["invoices", "Invoices"],
];

const STATUS_LABEL = {
  assigned: "Assigned",
  completed: "Completed",
  no_show: "No-show",
};

const PAYMENT_METHODS = [
  ["cheque", "Cheque"],
  ["netbanking", "Net banking / NEFT / RTGS"],
  ["upi", "UPI"],
  ["cash", "Cash"],
];

export default function HospitalDashboard() {
  const { user } = useAuth();
  const [dashboard, setDashboard] = useState(null);
  const [tab, setTab] = useState("active");
  const [cases, setCases] = useState([]);
  const [invoices, setInvoices] = useState([]);
  const [loading, setLoading] = useState(false);
  const [expandedId, setExpandedId] = useState(null);

  async function loadDashboard() {
    const { data } = await api.get("/hospital-console/dashboard");
    setDashboard(data);
  }

  async function loadCases(status) {
    setLoading(true);
    const { data } = await api.get("/hospital-console/patients", { params: { status } });
    setCases(data);
    setLoading(false);
  }

  async function loadInvoices() {
    setLoading(true);
    try {
      const { data } = await api.get("/hospital-console/invoices");
      setInvoices(data);
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => { loadDashboard(); }, []);

  useEffect(() => {
    if (tab === "active") loadCases("active");
    if (tab === "discharged") loadCases("discharged");
    if (tab === "invoices") loadInvoices();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [tab]);

  async function disputeDischarge(id, note) {
    await api.post(`/hospital-console/patients/${id}/dispute-discharge`, { note });
    loadCases("discharged");
  }

  async function reportPayment(invoiceId, payload) {
    await api.post(`/hospital-console/invoices/${invoiceId}/report-payment`, payload);
    loadInvoices();
  }

  return (
    <div className="max-w-5xl mx-auto px-5 py-12">
      <div className="flex items-center justify-between mb-2 flex-wrap gap-2">
        <h1 className="font-display text-3xl text-ink">{dashboard?.hospital_name || "Hospital Console"}</h1>
        <span className="text-sm text-ink/50">Signed in as {user?.full_name}</span>
      </div>
      <p className="text-ink/60 mb-8">
        Your concierge service, run end-to-end by ROSKYRO — our team opens every case and assigns a dedicated
        Relationship Officer, who alone confirms the patient's discharge (with a photo, as proof). This console is
        for you to see what's happening and pay your invoices — nothing here needs any handling from your staff.
        You'll be notified the moment a discharge is confirmed, and you can flag it here if something looks wrong.
      </p>

      {dashboard && (
        <div className="grid sm:grid-cols-2 md:grid-cols-4 gap-5 mb-10">
          <Stat label="Active patients" value={dashboard.active_patients} />
          <Stat label="Covered today" value={dashboard.today_assigned} />
          <Stat
            label="Awaiting today's officer"
            value={dashboard.today_unassigned}
            highlight={dashboard.today_unassigned > 0}
          />
          <Stat label="Discharged this month" value={dashboard.discharged_this_month} />
          <Stat label="Est. billing this month" value={`₹${dashboard.estimated_billing_this_month.toLocaleString("en-IN")}`} />
        </div>
      )}

      <div className="flex gap-6 border-b border-ink/10 mb-8 overflow-x-auto">
        {TABS.map(([key, label]) => (
          <button
            key={key}
            onClick={() => setTab(key)}
            className={`pb-3 text-sm font-semibold border-b-2 -mb-px whitespace-nowrap ${
              tab === key ? "border-violet text-violet" : "border-transparent text-ink/50"
            }`}
          >
            {label}
          </button>
        ))}
      </div>

      {loading && <p className="text-ink/50 mb-4">Loading…</p>}

      {tab === "invoices" && (
        <div className="space-y-4">
          {!loading && invoices.length === 0 && (
            <p className="text-ink/60">
              No invoices yet — invoices are generated by ROSKYRO once your discharged patients are ready to bill.
            </p>
          )}
          {invoices.map((inv) => (
            <InvoiceCard key={inv.id} inv={inv} onReportPayment={(payload) => reportPayment(inv.id, payload)} />
          ))}
        </div>
      )}

      {(tab === "active" || tab === "discharged") && (
        <div className="space-y-4">
          {cases.length === 0 && !loading && (
            <p className="text-ink/60">
              {tab === "active" ? "No active patients right now." : "No discharged patients yet."}
            </p>
          )}
          {cases.map((c) => (
            <PatientCard
              key={c.id}
              c={c}
              expanded={expandedId === c.id}
              onToggle={() => setExpandedId(expandedId === c.id ? null : c.id)}
              onDispute={(note) => disputeDischarge(c.id, note)}
            />
          ))}
        </div>
      )}
    </div>
  );
}

function PatientCard({ c, expanded, onToggle, onDispute }) {
  const [showDisputeForm, setShowDisputeForm] = useState(false);
  const [note, setNote] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [done, setDone] = useState(false);

  async function submitDispute(e) {
    e.preventDefault();
    setSubmitting(true);
    setError("");
    try {
      await onDispute(note);
      setShowDisputeForm(false);
      setDone(true);
    } catch (err) {
      setError(err.response?.data?.detail || "Could not submit this dispute.");
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div className="border border-ink/10 rounded-card p-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <div className="font-semibold text-ink">
            {c.patient_name}
            {c.patient_age != null && <span className="text-ink/40 font-normal"> · {c.patient_age} yrs</span>}
            {c.ward_or_room && <span className="text-ink/40 font-normal"> · {c.ward_or_room}</span>}
          </div>
          <div className="text-sm text-ink/50">
            Attendant: {c.attendant_name || "—"} · {c.attendant_phone}
          </div>
          <div className="text-sm text-ink/50">Admitted {c.admission_date}</div>
          {c.assigned_agent_name && (
            <div className="text-sm text-ink/50">Relationship Officer: {c.assigned_agent_name}</div>
          )}
          {c.short_note && <div className="text-sm text-ink/60 mt-1">{c.short_note}</div>}
        </div>
        <div className="text-right">
          <div className={`text-sm font-semibold ${c.today_officer_name ? "text-violet" : "text-clay"}`}>
            {c.status === "discharged" ? "Discharged" : c.today_officer_name ? `Today: ${c.today_officer_name}` : "Awaiting today's officer"}
          </div>
          <div className="text-xs text-ink/40 mt-1">
            {c.days_covered} day{c.days_covered === 1 ? "" : "s"} covered · ₹{c.billed_estimate.toLocaleString("en-IN")} billed
          </div>
        </div>
      </div>

      {c.status === "discharged" && c.hospital_notified_at && (
        <div className="text-xs text-ink/50 mt-3 border-t border-ink/10 pt-3">
          Discharge confirmed by {c.assigned_agent_name || "the assigned Relationship Officer"}
          {c.discharge_photo_at ? ", with a photo on file" : ""}. You were notified on{" "}
          {new Date(c.hospital_notified_at).toLocaleString()}.
          {c.hospital_disputed_at ? (
            <span className="block mt-1 font-semibold text-amber-600">
              You disputed this on {new Date(c.hospital_disputed_at).toLocaleString()} — ROSKYRO is reviewing it.
            </span>
          ) : null}
        </div>
      )}

      {c.alerts?.length > 0 && (
        <div className="space-y-1.5 mt-3">
          {c.alerts.map((a) => (
            <div
              key={a.code}
              className={`text-xs px-3 py-2 rounded-lg border font-medium ${
                a.severity === "critical"
                  ? "bg-rose-50 border-rose-200 text-rose-700"
                  : a.severity === "warning"
                  ? "bg-amber-50 border-amber-200 text-amber-700"
                  : "bg-slate-50 border-ink/10 text-ink/60"
              }`}
            >
              {a.message}
            </div>
          ))}
        </div>
      )}

      <div className="flex gap-3 mt-3 flex-wrap">
        <button onClick={onToggle} className="text-xs font-semibold text-violet">
          {expanded ? "Hide assignment history" : "View assignment history"}
        </button>
        {c.can_dispute_discharge && !showDisputeForm && !done && (
          <button onClick={() => setShowDisputeForm(true)} className="text-xs font-semibold text-clay ml-auto">
            This discharge looks wrong
          </button>
        )}
        {done && <span className="text-xs font-semibold text-green-700 ml-auto">Dispute submitted — ROSKYRO will follow up.</span>}
      </div>

      {error && <p className="text-xs text-clay mt-2">{error}</p>}

      {showDisputeForm && (
        <form onSubmit={submitDispute} className="mt-3 border-t border-ink/10 pt-3 space-y-2">
          <label className="block">
            <span className="text-xs text-ink/50 block">What's wrong? (a quick note is enough — ROSKYRO will follow up)</span>
            <textarea
              required rows={3} value={note} onChange={(e) => setNote(e.target.value)}
              className="text-sm border border-ink/15 rounded-lg px-3 py-2 w-full mt-1"
              placeholder="e.g. This patient actually went home two days earlier than shown here."
            />
          </label>
          <div className="flex gap-2">
            <button disabled={submitting} className="text-sm font-semibold px-4 py-2 rounded-full bg-clay text-white disabled:opacity-60">
              {submitting ? "Submitting…" : "Submit dispute"}
            </button>
            <button type="button" onClick={() => setShowDisputeForm(false)} className="text-xs font-semibold text-ink/50">
              Cancel
            </button>
          </div>
        </form>
      )}

      {expanded && (
        <div className="mt-3 border-t border-ink/10 pt-3 space-y-1.5">
          {c.assignments.length === 0 && (
            <p className="text-xs text-ink/40">
              {c.assigned_agent_name
                ? `${c.assigned_agent_name} covers this patient every day — no day-by-day rows logged.`
                : "No officer assigned yet."}
            </p>
          )}
          {c.assignments.map((a) => (
            <div key={a.id} className="text-sm flex flex-wrap gap-2 items-baseline">
              <span className="font-semibold text-ink">{a.date}</span>
              <span className="text-ink/70">{a.agent_name}</span>
              <span className={`text-xs ${a.status === "no_show" ? "text-clay font-semibold" : "text-ink/40"}`}>{STATUS_LABEL[a.status] || a.status}</span>
              {a.note && <span className="text-xs text-ink/40 ml-auto">{a.note}</span>}
            </div>
          ))}
        </div>
      )}
    </div>
  );
}

function InvoiceCard({ inv, onReportPayment }) {
  const [showForm, setShowForm] = useState(false);
  const [method, setMethod] = useState("upi");
  const [reference, setReference] = useState("");
  const [note, setNote] = useState("");
  const [submitting, setSubmitting] = useState(false);
  const [error, setError] = useState("");

  const canReport = inv.status === "unpaid";

  async function submit(e) {
    e.preventDefault();
    setSubmitting(true);
    setError("");
    try {
      await onReportPayment({ method, reference: reference || null, note: note || null });
      setShowForm(false);
    } catch (err) {
      setError(err.response?.data?.detail || "Could not save this payment report.");
    } finally {
      setSubmitting(false);
    }
  }

  const statusStyle = {
    paid: "bg-green-100 text-green-700",
    payment_reported: "bg-blue-50 text-blue-700",
    unpaid: "bg-amber-50 text-amber-700",
  }[inv.status] || "bg-amber-50 text-amber-700";

  const statusLabel = {
    paid: "paid",
    payment_reported: "payment reported — ROSKYRO verifying",
    unpaid: "unpaid",
  }[inv.status] || inv.status;

  return (
    <div className="border border-ink/10 rounded-card p-5">
      <div className="flex flex-wrap items-start justify-between gap-3">
        <div>
          <div className="font-semibold text-ink">
            {inv.period_start} → {inv.period_end}
          </div>
          <div className="text-sm text-ink/50">
            {inv.case_count} patient{inv.case_count === 1 ? "" : "s"} discharged and billed
          </div>
        </div>
        <div className="text-right">
          <div className="font-display text-xl text-ink">₹{inv.total_amount.toLocaleString("en-IN")}</div>
          <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${statusStyle}`}>{statusLabel}</span>
        </div>
      </div>
      {inv.status === "paid" && (
        <div className="text-xs text-ink/50 mt-2">
          Paid {new Date(inv.paid_at).toLocaleDateString()}
          {inv.payment_reference ? ` · ref: ${inv.payment_reference}` : ""}
        </div>
      )}
      {inv.status === "payment_reported" && (
        <div className="text-xs text-ink/50 mt-2">
          You reported this as paid by {inv.reported_payment_method} on{" "}
          {inv.reported_at ? new Date(inv.reported_at).toLocaleDateString() : ""}
          {inv.reported_payment_reference ? ` · ref: ${inv.reported_payment_reference}` : ""} — ROSKYRO is verifying it.
        </div>
      )}
      <div className="mt-3 border-t border-ink/10 pt-3 space-y-1.5">
        {inv.cases.map((c) => (
          <div key={c.case_id} className="text-sm flex flex-wrap gap-2 justify-between">
            <span className="text-ink/80">{c.patient_name}</span>
            <span className="text-ink/50">
              {c.days_covered} day{c.days_covered === 1 ? "" : "s"} · ₹{c.amount.toLocaleString("en-IN")}
            </span>
          </div>
        ))}
      </div>

      {canReport && !showForm && (
        <button onClick={() => setShowForm(true)} className="text-xs font-semibold text-violet mt-3">
          I've paid this — report payment
        </button>
      )}

      {error && <p className="text-xs text-clay mt-2">{error}</p>}

      {canReport && showForm && (
        <form onSubmit={submit} className="mt-3 border-t border-ink/10 pt-3 space-y-3">
          <label className="block">
            <span className="text-xs text-ink/50 block">Paid by</span>
            <select value={method} onChange={(e) => setMethod(e.target.value)} className="input">
              {PAYMENT_METHODS.map(([value, label]) => (
                <option key={value} value={value}>{label}</option>
              ))}
            </select>
          </label>
          <label className="block">
            <span className="text-xs text-ink/50 block">Reference (cheque no. / UTR / UPI ref — optional)</span>
            <input value={reference} onChange={(e) => setReference(e.target.value)} className="input" />
          </label>
          <label className="block">
            <span className="text-xs text-ink/50 block">Note (optional)</span>
            <input value={note} onChange={(e) => setNote(e.target.value)} className="input" />
          </label>
          <div className="flex gap-2">
            <button disabled={submitting} className="text-sm font-semibold px-4 py-2 rounded-full bg-violet text-white disabled:opacity-60">
              {submitting ? "Saving…" : "Report payment"}
            </button>
            <button type="button" onClick={() => setShowForm(false)} className="text-xs font-semibold text-ink/50">
              Cancel
            </button>
          </div>
          <style>{`.input { width: 100%; margin-top: 4px; border: 1px solid rgba(0,0,0,0.15); border-radius: 0.5rem; padding: 0.6rem 0.9rem; }`}</style>
        </form>
      )}
    </div>
  );
}

function Stat({ label, value, highlight }) {
  return (
    <div className={`rounded-card p-5 border ${highlight ? "border-clay bg-clay/5" : "border-ink/10"}`}>
      <div className="text-2xl font-display text-ink">{value}</div>
      <div className="text-sm text-ink/50">{label}</div>
    </div>
  );
}
